services:
  # FastAPI приложение
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./certificates:/etc/ssl/certs  # Монтируем сертификаты в контейнер
    env_file:
      - ./.env
    environment:
      - SSL_CERT_PATH=/etc/ssl/certs/root.crt  # Указываем путь к сертификату
    networks:
      - backend_network

  # Telegram бот
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - backend_network


networks:
  backend_network:
    driver: bridge
